### PR TITLE
Clean up and tests

### PR DESCRIPTION
**Pull request by corny**
See commit messages for details.
Renaming of exported fields breaks compatibility!

### CODE REVIEW

**Comment by abourget** [comment]
Hey thanks a whole lot :)

**Comment by corny** [comment]
Thanks for merging. Do you want to use Travis CI? I could add a `.travis.yml`

**Comment by abourget** [comment]
Go ahead.. Are you using this extensively ?

**Comment by corny** [comment]
Travis or this library?

**Comment by abourget** [comment]
heh I mean this library ? because perhaps I could give you write access..

**Comment by corny** [comment]
Not really. I just use it for my [zammad connector](https://github.com/digineo/zammad-asterisk) and it's working very well. Good work!

**Comment by corny** [comment]
Thanks. If I find some time I will write more tests ;-)

**Pull request merged**
