### PR TITLE
Can not compile, napping change session delete func

### PR DESCRIPTION
**Pull request by kor44**
When try to build has following error

.\rest.go:34: not enough arguments in call to c.session.Delete

### CODE REVIEW

**Comment by abourget** [comment]
I've merged another PR, can you check what's up with this one now ?

thanks!

**Comment by kor44** [comment]
Now it's OK

**Comment by abourget** [comment]
It says there are conflicts.. this breaks at compile-time ??

**Comment by kor44** [comment]
I have no errors.
Build package is OK

**Comment by abourget** [comment]
Ok, I mean, pull from the latest version, and then try again.. I've since merged another PR, that's why :)

**Comment by abourget** [comment]
Reopen if still needed.

**Pull request closed without merging**
